# Generated by Django 4.0 on 2022-07-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image_name_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='skills')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='posts', to='blog.Skill'),
        ),
    ]
