# Generated by Django 4.0 on 2022-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_skill_name_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Skill'),
        ),
    ]
